/**
 * 资源更新
 */

 export enum EnumAssetsEvents {
     UPDATE_GAME_VERSION = "UPDATE_GAME_VERSION",
     CHECK_UPDATE = "CHECK_UPDATE",
     START_UPDATE = "START_UPDATE",
     NEW_VERSION_FOUND = "NEW_VERSION_FOUND",
     UPDATE_INIT_ERROR = "UPDATE_INIT_ERROR",
     ALREADY_UP_TO_DATE = "ALREADY_UP_TO_DATE",
     UPDATE_PROGRESSION = "UPDATE_PROGRESSION",
     UPDATE_FINISHED = "UPDATE_FINISHED",
 }